"""JWT authentication + password hashing + auth decorators."""
import functools
import logging
import os
from datetime import datetime, timedelta

import jwt
from flask import request, jsonify, g
from werkzeug.security import generate_password_hash, check_password_hash

from .config import Config
from .models import User, Company

logger = logging.getLogger(__name__)

# Check if running in microservice mode
MICROSERVICE_MODE = os.getenv("MICROSERVICE_MODE", "false").lower() == "true"

JWT_SECRET = os.getenv("JWT_SECRET_KEY", Config.SECRET_KEY or "dev-secret")
JWT_EXP_HOURS = int(os.getenv("JWT_EXPIRATION_HOURS", "24"))


def hash_password(password: str) -> str:
    return generate_password_hash(password)


def verify_password(password_hash: str, password: str) -> bool:
    try:
        return check_password_hash(password_hash, password)
    except Exception:
        return False


def _resolve_related_company_ids(company_id: int) -> list:
    if not company_id:
        return []
    try:
        rows = Company.query.filter_by(parent_company_id=company_id, is_active=True).all()
        return [r.id for r in rows if r.id]
    except Exception:
        return []


def generate_token(
    user: User,
    company_id: int = None,
    branch_id: int = None,
    related_company_ids: list = None,
    company_fk: int = None,
) -> str:
    effective_company_id = company_id if company_id is not None else user.company_id
    effective_branch_id = branch_id if branch_id is not None else user.branch_id
    related_ids = related_company_ids
    if related_ids is None and effective_company_id:
        related_ids = [effective_company_id] + _resolve_related_company_ids(effective_company_id)
    payload = {
        "sub": str(user.id),
        "username": user.username,
        "company_id": effective_company_id,
        "company_fk": company_fk,  # SOURCE company id for data isolation (may be None)
        "branch_id": effective_branch_id,
        "is_admin": user.is_admin(),
        "roles": [r.name for r in user.roles()],
        "related_company_ids": related_ids or [],
        "exp": datetime.utcnow() + timedelta(hours=JWT_EXP_HOURS),
        "iat": datetime.utcnow(),
    }
    return jwt.encode(payload, JWT_SECRET, algorithm="HS256")


def decode_token(token: str):
    return jwt.decode(token, JWT_SECRET, algorithms=["HS256"], options={"verify_aud": False})


def _extract_token() -> str:
    auth = request.headers.get("Authorization", "").strip()
    # Handle case-insensitive Bearer scheme
    if auth.lower().startswith("bearer "):
        token = auth[7:].strip()
        # Remove all embedded whitespace/newlines that break JWT parsing
        token = ''.join(token.split())
        return token
    return ""


def current_user_context() -> dict:
    """Return the user context attached by require_auth (or microservice token)."""
    # Check microservice context first if in microservice mode
    if MICROSERVICE_MODE:
        microservice_ctx = getattr(g, "microservice_user_ctx", {}) or {}
        if microservice_ctx:
            return microservice_ctx
    
    # Fall back to traditional auth context
    return getattr(g, "user_ctx", {}) or {}


def require_auth(fn):
    """Protect an endpoint; attaches g.user_ctx with id/company/branch/roles.
    In microservice mode, validates token from main server instead."""
    @functools.wraps(fn)
    def wrapper(*args, **kwargs):
        token = _extract_token()
        if not token:
            return jsonify({"success": False, "error": "Authentication required"}), 401
        
        # Microservice mode: try validating token from main server first
        if MICROSERVICE_MODE:
            from .microservice_auth import extract_user_from_token
            
            user_ctx = extract_user_from_token(token)
            if user_ctx:
                g.microservice_user_ctx = user_ctx
                return fn(*args, **kwargs)
            # If microservice validation failed, fall through to traditional auth
        
        # Traditional mode: validate token generated by this app
        try:
            payload = decode_token(token)
        except jwt.ExpiredSignatureError:
            return jsonify({"success": False, "error": "Token expired"}), 401
        except Exception:
            return jsonify({"success": False, "error": "Invalid token"}), 401

        user = User.query.get(int(payload.get("sub", 0)))
        if not user or not user.is_active:
            return jsonify({"success": False, "error": "User not found or inactive"}), 401

        company_id = payload.get("company_id") or user.company_id
        branch_id = payload.get("branch_id") or user.branch_id
        company_fk = payload.get("company_fk")  # Extract company_fk from JWT (for token login)
        related_ids = payload.get("related_company_ids")
        if related_ids is None and company_id:
            related_ids = [company_id] + _resolve_related_company_ids(company_id)

        # Get roles: use database roles if available, otherwise use JWT payload roles
        user_roles = [r.name for r in user.roles()]
        if not user_roles and payload.get("roles"):
            # User has no database roles, use roles from JWT (for token login)
            user_roles = payload.get("roles", [])
            if isinstance(user_roles, str):
                user_roles = user_roles.split()

        g.user_ctx = {
            "user_id": user.id,
            "username": user.username,
            "company_id": company_id,
            "company_fk": company_fk,  # Include company_fk for proper FK filtering
            "branch_id": branch_id,
            "related_company_ids": related_ids or [],
            "is_admin": user.is_admin(),
            "roles": user_roles,
        }
        return fn(*args, **kwargs)
    return wrapper


def optional_auth(fn):
    """Like require_auth but does not reject anonymous requests.
    Works with both traditional auth and microservice tokens."""
    @functools.wraps(fn)
    def wrapper(*args, **kwargs):
        token = _extract_token()
        g.user_ctx = {}
        
        # Microservice mode: try to extract user from token
        if MICROSERVICE_MODE and token:
            from .microservice_auth import extract_user_from_token
            
            user_ctx = extract_user_from_token(token)
            if user_ctx:
                g.microservice_user_ctx = user_ctx
                return fn(*args, **kwargs)
            # If microservice validation failed, fall through to traditional auth
        
        # Traditional mode: try to extract user from token
        if token:
            try:
                payload = decode_token(token)
                user = User.query.get(int(payload.get("sub", 0)))
                if user and user.is_active:
                    company_id = payload.get("company_id") or user.company_id
                    branch_id = payload.get("branch_id") or user.branch_id
                    related_ids = payload.get("related_company_ids")
                    if related_ids is None and company_id:
                        related_ids = [company_id] + _resolve_related_company_ids(company_id)

                    g.user_ctx = {
                        "user_id": user.id,
                        "username": user.username,
                        "company_id": company_id,
                        "branch_id": branch_id,
                        "related_company_ids": related_ids or [],
                        "is_admin": user.is_admin(),
                        "roles": [r.name for r in user.roles()],
                    }
            except Exception:
                pass
        return fn(*args, **kwargs)
    return wrapper
